branch-defaults:
  master:
    environment: ydm-web
global:
  application_name: ydm-web
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-cli
  sc: git
